obstacle_range: 15.0
raytrace_range: 15.0
robot_radius: 0.5
inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: "base_link", data_type: LaserScan, topic: "scan", marking: true, clearing: true}

